### ISSUE TITLE
Wallets not accepting private key format

### ISSUE THREAD

**Issue by Cryptovesturr124355** [HorizenOfficial/zencash-swing-wallet-ui#160]
Hi, none of the zen supported wallets I use seem to be accepting the “format” of my private key. I am typing it in just as I wrote it when opening my desktop wallet. I know my private key but I have been having trouble accessing the wallet still

**Comment by uanl979** [comment]
Hi @Cryptovesturr124355 

Have you solved this issue already? Please let me know if your issue still persists. 

Regards
Rubén
