### ISSUE TITLE
Witness for note commitment is null

### ISSUE THREAD

**Issue by Pigman91** [HorizenOfficial/zencash-swing-wallet-ui#166]
Hey guys, I have a problem with my wallet.

I have Horizen Swing Wallet 0.90.2, where I have Z private address with some amount.
I want to send this amount to a new wallet but i keep getting this error message.

<a href='https://postimg.cc/fJWLvzjH' target='_blank'><img src='https://i.postimg.cc/fJWLvzjH/V-st-i-ek.png' border='0' alt='V-st-i-ek'/></a>

Could someone of you help me please?

**Comment by lander86** [comment]
Hello @Pigman91, to fix this issue try to follow these steps : 

- export z-address private key of the address with the unspendable note
- stop swing
- take backup:
`cd $HOME/Library/Applicaction\ Support/Zen && mkdir backup && mv {blocks,chainstate,wallet.dat} backups`
- start zend with -connect= to force block height 0: in a second terminal window
 `zend -connect=127.0.0.1:12345`
- wait for start, then import z-addr PK:
`zen-cli z_importkey $key_from_step_1`
- stop zend:
`zen-cli stop`
- start swing normally and wait until fully synced
- send the remaining z_addr balance to an address of choice, it should be spendable now
- stop swing, move back backup folders:
`cd $HOME/Library/Applicaction\ Support/Zen && rm {blocks,chainstate,wallet.dat} && mv backups/{blocks,chainstate,wallet.dat} .`
- start swing again, after syncing last couple of blocks all should be good

Ps : Please remember that absolute paths to zend/zen-cli have to be provided.

**Comment by lander86** [comment]
Hello @Pigman91, 

I haven't received any update from you for a while so i'm going to close this issue. I hope your problem has been solved.

Should you need any further help or support with this, please let us know!
